name: Project
fields:
  - name: id
    type: primaryKey
    description: Unique ID
    forCreate: false
  - name: title
    type: string
    description: Project title
  - name: description
    type: string
    description: Project description
